apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - web-configmap.yaml
  - web-deployment.yaml
  - web-service.yaml
  - strapi-configmap.yaml
  - strapi-deployment.yaml
  - strapi-service.yaml
  - strapi-db-service.yaml
  - strapi-db-statefulset.yaml
  - matomo-configmap.yaml
  - matomo-pvc.yaml
  - matomo-deployment.yaml
  - matomo-service.yaml
  - matomo-db-service.yaml
  - matomo-db-statefulset.yaml
