apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-config
data:
  MATOMO_DATABASE_HOST: matomo-db
  MATOMO_DATABASE_ADAPTER: mysql
  MATOMO_DATABASE_TABLES_PREFIX: matomo_
  MATOMO_DATABASE_DBNAME: matomo
