apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasserball-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasserball-web
  template:
    metadata:
      labels:
        app: wasserball-web
    spec:
      containers:
        - name: web
          image: ghcr.io/davidvanelk/wasserball-public-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
          envFrom:
            - configMapRef:
                name: wasserball-web-config
            - secretRef:
                name: wasserball-web-secret
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
