apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - web-ingress.yaml
  - matomo-ingress.yaml

patches:
  - path: web-scale-patch.yaml
    target:
      kind: Deployment
      name: wasserball-web