apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wasserball-web
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-traefik-https-redirect@kubernetescrd,default-wasserball-web-basic-auth@kubernetescrd
